### ISSUE TITLE
Getting error on using same example after updating version to 3.0.0

### ISSUE THREAD

**Issue by RaminderRandhawa91** [Arction/lcjs-example-0302-groupedBars#1]
Getting this exception 
lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29 Uncaught TypeError: t.split is not a function
    at t.uL (lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29)
    at i.Mn (lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29)
    at n.Mn (lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29)
    at i.plot (lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29)
    at n.ke (lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29)
    at lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29
    at Array.reduce (<anonymous>)
    at s.c.rT (lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29)
    at s.ke (lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29)
    at i.<anonymous> (lcjs.iife.js?v=tRroT68H5qMsFw3j3m4n7nfsLOkhh6auGlVAhpVMX1Y:29)

**Comment by Snekw** [comment]
I can't reproduce this error. More information is needed in order for me to be able to help you.

1. This example doesn't use the lcjs.iife.js file so what kind of project is this issue happening in? 
2. What features of LCJS are you using?
3. What browser are you using?
4. Can you post a minimal reproducible example where this issue happens?

**Comment by RaminderRandhawa91** [comment]
Resolved this issue. 
The issue was caused on **setTextFormatter** as it accepts only string values and I was giving numerical value for **name**

`    const addGroups = (names) => {
            for (const name of names)
                groups.push({
                    name,
                    tick: axisX.addCustomTick(UIElementBuilders.AxisTick)
                        .setGridStrokeLength(0)
                        **.setTextFormatter((_) => name)**
                        .setMarker((marker) => marker
                            .setTextFillStyle(new SolidFill({ color: ColorRGBA(170, 170, 170) }))
                        )
                })
        }`
